---
- name: Compile list of traefik container labels
  set_fact:
    all_container_labels: "{{ container_labels }} + {{ result }}"
  vars:
    prefix: "traefik.http.{{ container_name }}."
    a_list: "{{ traefik_router_labels }}"
    result: "{{ [prefix] | product(a_list) | map('join') | list }}"

- name: Set facts for tmp container and systemd name
  set_fact:
    tmp_name: "{{ name }}-tmp"
    tmp_container_name: "{{ container_name }}-tmp"

- name: Ensure normal application exists
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    container_labels: "{{ all_container_labels }}"

- name: Remove image
  docker_image:
    name: "{{ container_image }}"
    state: absent
    force_absent: yes
  when: (force_install|default(false)|bool == true)

- name: Load new image
  docker_image:
    name: "{{ container_image }}"
    state: present
  when: (force_install|default(false)|bool == true)

- name: Compile list of traefik container labels
  set_fact:
    traefik_tmp_container_labels: "{{ result }}"
  vars:
    prefix: "traefik.http.{{ container_name }}-tmp."
    a_list: "{{ traefik_router_labels }}"
    result: "{{ [prefix] | product(a_list) | map('join') | list }}"
  when: (rolling_update|default(false)|bool == true)

- name: create tmp application
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    name: "{{ tmp_name }}"
    container_name: "{{ tmp_container_name }}"
    container_labels: "{{ all_container_labels }}"
  when: (rolling_update|default(false)|bool == true)

- name: wait for service to come up
  pause:
    minutes: "{{ service_startup_time }}"
  when: (rolling_update|default(false)|bool == true)

- name: Restart normal systemd service
  systemd:
    state: restarted
    name: "{{ name }}"
  when: (rolling_update|default(false)|bool == true)

- name: wait for service to come up
  pause:
    minutes: "{{ service_startup_time }}"
  when: (rolling_update|default(false)|bool == true)

- name: Stop tmp systemd service
  systemd:
    state: stopped
    name: "{{ tmp_name }}"
  when: (rolling_update|default(false)|bool == true)

- name: Remove systemd service
  file:
    path: "/etc/systemd/system/{{ tmp_name }}_container.service"
    state: absent

- name: Reload systemd deamon
  systemd:
    daemon_reload: yes
